apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-db-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: python-app-secrets 
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: production/database/credentials
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: production/database/credentials
        property: password
    - secretKey: JWT_SECRET
      remoteRef:
        key: production/app/jwt
        property: secret
